### ISSUE TITLE
Cannot initialize new device/accessory

### ISSUE THREAD

**Issue by g8trader19** [michaelahern/homebridge-wattbox-ip#5]
I had my devices setup right but then after setting up as child bridge I get the following log error. Same error when I deleted plugin, accessories, and cache. 

[01/09/2023, 01:30:09] [homebridge-wattbox-ip] [WattBox 800 UPS IP-12] write after end
[01/09/2023, 01:30:09] [homebridge-wattbox-ip] [WattBox 800 UPS IP-12] Cannot initialize new device/accessory, check configuration!

{
    "devices": [
        {
            "name": "WattBox 800 UPS IP-12",
            "host": "xxxxx",
            "username": "xxxxxx",
            "password": "xxxxx",
            "serviceTag": "xxxxx",
            "outletsResetOnly": true
        },
        {
            "name": "WattBox 800 IP-6",
            "host": "xxxxx",
            "username": "xxxx",
            "password": "xxxxxx",
            "serviceTag": "xxxxxx"
        }
    ],
    "platform": "WattBox IP",
    "_bridge": {
        "username": "xxxxx",
        "port": 
    }
}

**Comment by michaelahern** [comment]
What firmware version are your WattBox devices running on? I noticed some occasional issues where the WattBox devices would stop accepting new connections until a reset, but since upgrading to 2.5.0.8 I have not experienced this issue.

https://www.control4.com/docs/product/wattbox-800-series/release-notes/english/latest//wattbox-800-series-release-notes-rev-g.pdf

**Comment by michaelahern** [comment]
Latest v0.3.0 includes additional connection fixes. This in combination with upgrading the firmware to 2.5.0.8 should resolve initialization/startup errors.
